### ISSUE TITLE
Wiki Page Home

### ISSUE THREAD

**Issue by ajansel** [npartovi/Destructables#1]
# Wiki Page Home

- [x] Is the first page you see upon entering the wiki
- [x] Contains a welcome message
  - You have two, you should remove one of them
- [x] Contains a link/placeholder for a link to the live page
  - This can just be a link to GitHub, App Academy, or Heroku main page for now and then once you have a live link you can change it.
- [x] All links in the right sidebar should contain each wiki page and link to the correct page
- [x] Correctly formatted
    - [x] each wiki page is listed in bullet points
    - [x] all links route the correct page

# Comments:
Looks good! Once you complete the above, comment on here to let me know and then I can close the issue!

**Comment by npartovi** [comment]
Yo AJ I finished the home page issues.

**Comment by ajansel** [comment]
Looks good! Done here
