### ISSUE TITLE
MVP List

### ISSUE THREAD

**Issue by ajansel** [npartovi/Destructables#2]
# MVP List

- [x] Should have 7 MVPs.
    - [x] 3 of those are User Auth, Heroku, and Production README.
    - [x] The other 4 are from the [MVP List](https://github.com/appacademy/curriculum/blob/master/full-stack-project/proposal/mvp-list.md) or they have clarified them with you
- [x] Contains a description sentence of the app
- [x] At least one CRUD feature, which states what CRUD operations are planned (creation, reading, updating, deletion)
- [x] Estimates how long it will take the code each MVP
- [x] Each App specific MVP needs the following bullet points are added:
    + Adequate styling
    + Smooth, bug-free navigation
    + Seeded with info to demonstrate this feature

- [x] Correctly formatted
    - [x] MVPs are listed in an ordered list
    - [x] Each MVP is broken down into bullet points

# Comments:
This needs to be updated / redesigned. See [Bluebird MVP List](https://github.com/appacademy/bluebird/wiki/mvp-list) for an example.

**Comment by npartovi** [comment]
fixed all the issues except the estimation for each MVP item.

**Comment by npartovi** [comment]
estimations are now done.

**Comment by ajansel** [comment]
Great work! This is excellent. I only have a few small things. Can you add deleting for articles and comments as a bullet as well? That way they are full CRUD. Also, they should be able to delete photos and videos. And likes should be bonus since we only require you to have 4 major MVPs.

**Comment by ajansel** [comment]
Good to go!
