### ISSUE TITLE
Database Schema

### ISSUE THREAD

**Issue by ajansel** [npartovi/Destructables#3]
# Database Schema
- [x] Contains correct datatypes
- [x] Contains appropriate constraints/details
    - [x] primary key
    - [x] not null
    - [x] unique
      - These need to be added. Probably article titles, user usernames and emails, the combination of steps and article_id, the combination of article_id and user_id for favorites, etc. 
    - [x] indexed
      - The combinations that I mentioned above for `unique` in addition to all the foreign keys,  
    - [x] foreign key
      - These need marked as well 
- [x] Contains bullet points after the table that state which foreign keys will reference to which table, or references to the associations which will be made
  - Great job with the associations, not just add the additional information for the foreign keys. See [bluebird schema](https://github.com/appacademy/bluebird/wiki/schema) for an example. 

- [x] Correctly formatted
    - [x] schema is written in a table format
    - [x] the table's name are `back_ticked`
      - This needs completed
    - [x] the table header column names are bolded
      - This needs completed
    - [x] columns names are lowercased and snaked_cased and `back_ticked`
      - Change table names to lowercase

# Comments:
- It seems articles should also have a "top level" video and image maybe? In addition to the ones within their `steps`. Does that seem right? If so, you could do two img_urls within the articles table?
- My recommendation would be to have users have img_urls for a profile picture. This will ensure that there are not profiles without pictures that would make the site bare. I can explain more on this when we meet as well if you'd like. There's an easy way to set a default to give you the ability to add increased flexibility later.

**Comment by npartovi** [comment]
done with the additional items that were left from when we spoke on april 3, 2018

**Comment by ajansel** [comment]
Awesome, thank you! Good here
