### ISSUE TITLE
Routes

### ISSUE THREAD

**Issue by ajansel** [npartovi/Destructables#4]
# Routes

- [x] Routes accurately reflect MVPs and Component Hierarchy
- [x] Covers the frontend functionality of the site through routes that match to the wireframes
- [x] Contains the following sections: HTML, API Endpoints(Backend), and Frontend Routes
  - Add your static pages HTML route and you should be good to go
- [x] Each route has a description
- [x] API Endpoint routes contains wildcard variables written in `snake_case`
- [x] Frontend routes contains wildcard variables written in `camelCase`
- [x] Have API routes that will allow the front end to get all info it needs and does not have unneeded routes:
    + probably doesn't need a `GET likes` api endpoint bc that info comes through the post show
- [x] Correctly formatted
    - [x] Routes are displayed with `inline coding text` (backticks)

# Comments:
- gets the steps written for a article --> `an article`
- You won't need your first route for steps (the index type route). Instead when you do any request for an article you'll send up the steps with it. Same is true with your first `get` request for comments
- Create for steps will need to be nested so that it can get the `article_id` from the params
- You will probably want a `show` method for a single step as well
- You will need a delete for comments as well so that it is full CRUD

**Comment by npartovi** [comment]
- added delete route for comments
- remove the get request for steps and comment
- nested create step request under article/:id
- dont need show for single step as instructables does not do that. they show all steps with images on the show page itself.
- added get request to get steps under a particular article based on the article id
